require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/welcomes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Welcome. As you add validations to Welcome, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Welcome.create! valid_attributes
      get welcomes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      welcome = Welcome.create! valid_attributes
      get welcome_url(welcome)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_welcome_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      welcome = Welcome.create! valid_attributes
      get edit_welcome_url(welcome)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Welcome" do
        expect {
          post welcomes_url, params: { welcome: valid_attributes }
        }.to change(Welcome, :count).by(1)
      end

      it "redirects to the created welcome" do
        post welcomes_url, params: { welcome: valid_attributes }
        expect(response).to redirect_to(welcome_url(Welcome.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Welcome" do
        expect {
          post welcomes_url, params: { welcome: invalid_attributes }
        }.to change(Welcome, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post welcomes_url, params: { welcome: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested welcome" do
        welcome = Welcome.create! valid_attributes
        patch welcome_url(welcome), params: { welcome: new_attributes }
        welcome.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the welcome" do
        welcome = Welcome.create! valid_attributes
        patch welcome_url(welcome), params: { welcome: new_attributes }
        welcome.reload
        expect(response).to redirect_to(welcome_url(welcome))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        welcome = Welcome.create! valid_attributes
        patch welcome_url(welcome), params: { welcome: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested welcome" do
      welcome = Welcome.create! valid_attributes
      expect {
        delete welcome_url(welcome)
      }.to change(Welcome, :count).by(-1)
    end

    it "redirects to the welcomes list" do
      welcome = Welcome.create! valid_attributes
      delete welcome_url(welcome)
      expect(response).to redirect_to(welcomes_url)
    end
  end
end
